sudo: false

language: php
php:
  - 5.6
  - 7.2
before_script:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then composer require --dev --no-update phpunit/phpunit ~4; fi
  - composer install
  - cd tests
script: phpunit -v


jobs:
  include:
    - stage: docker release
      php: 5.6
      if: tag IS present
      script:
        - docker build -t allovince/evathumber .
        - docker tag allovince/evathumber allovince/evathumber:$TRAVIS_TAG
        - docker images
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        - docker push allovince/evathumber:latest;
        - docker push allovince/evathumber:$TRAVIS_TAG;
